### ISSUE TITLE
Request for the RAW RNA-seq data and clinical data

### ISSUE THREAD

**Issue by Hjiao1993** [hammerlab/multi-omic-urothelial-anti-pdl1#6]
Dear Tavi,

I am a urologist from Central South University. Recently, our team are doing a research to investigate the predictors of response to immune checkoints in bladder cancer. We want to validate our conclusions in some external immune-associated data set.  We found that your data set was valuable and would give us great help.
Could you inform me if the raw RNA seq data and clinical information used in this analysis are publicly available for download somewhere?

Thanks,
Jiaohu

**Comment by Hjiao1993** [comment]
Dear Tavi,

My email address is hujiao@csu.edu.cn.

**Comment by tavinathanson** [comment]
Hi Jiaohu,

Thanks for your interest! The raw data is now available via dbGaP Authorized Access: https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001743.v1.p1

Best,
Tavi

**Comment by Hjiao1993** [comment]
Dear Tavi,
Thank you very much for your help. 


| |
胡姣
|
|
hujiao1993@163.com
|
签名由网易邮箱大师定制
