### ISSUE TITLE
Was the RNA-seq data here included in IMvigor210CoreBiologies R package?

### ISSUE THREAD

**Issue by learn-lx-zhu** [hammerlab/multi-omic-urothelial-anti-pdl1#7]
@tavinathanson 
Hi there,

I noticed that the data in this article and the data from the work of Mariathasan et al. both come from the IMvigor210 trial. However, the naming conventions for the patients in the two datasets are different, which makes it difficult for me to determine if they are the same. I was wondering if the RNA-seq data provided in this article is included in the `IMvigor210CoreBiologies` R data package that Mariathasan et al. provided (PMID:29443960). I have reached out to the corresponding author for clarification but do not received a response, so I was curious if you know the details on this matter.

Thank you!

**Comment by tavinathanson** [comment]
@learn-lx-zhu unfortunately I don't know the answer. However, if it's helpful, note that the raw underlying data we used is available on dbGaP at http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001743.v1.p1
